### ISSUE TITLE
ICE candidate sending possibly not retried in matroyshka mode?

### ISSUE THREAD

**Issue by dbkr** [element-hq/element-call#746]
### Steps to reproduce

In a rageshake, connectivity between two participants seems to have failed due to a request timeout sending ICE candidates in widget mode. It looks like the client may not be retrying as no candidates ever get sent in this direction.

```
2022-11-10T09:46:07.674Z I Call 1668073552480KT71qcJDspxaADma failed to send candidates. Retrying in 1000ms Request timed out
Error: Request timed out
    at https://element-call.netlify.app/assets/index.29c048b5.js:15:34988
    at i (https://element-call.netlify.app/assets/index.29c048b5.js:129:5148)
```

### Will you send logs?

Yes

**Comment by fkwp** [comment]
This is predating our move to LiveKit. Please reopen if that is still an issue
